version: '3'
services:
  api:
    image: golang:latest
    container_name: icx-api-go
    build: './api'
    ports:
      - 8080:8080
    volumes:
      - ./api:/go/src/app
    command: go run main.go
    depends_on: 
      - 'db'
  web:
    container_name: icx-api-web-page
    image: 'nginx'
    build: ./web
    ports: 
        - 80:80
    volumes:
      - './web'
  db:
    image: mongo:3.6.1
    container_name: icx-db-mongo
    env_file: 
        - .env
    environment: 
        - MONGO_INITDB_DATABASE=${MONGODB_DBNAME}
        - MONGO_INITDB_USERNAME=${MONGODB_USERNAME}
        - MONGO_INITDB_PASSWORD=${MONGODB_PASSWORD}
    volumes: 
        - mongodb:/data/db
    ports:
        - 27017:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config: